"""add market_products price_history price_comparisons

Revision ID: 96a6c9decf3b
Revises: d2dc1ec2dd72
Create Date: 2026-09-03 10:04:14.839222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96a6c9decf3b'
down_revision: Union[str, Sequence[str], None] = 'd2dc1ec2dd72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('source_product_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('product_url', sa.String(length=2048), nullable=True),
    sa.Column('image_url', sa.String(length=2048), nullable=True),
    sa.Column('availability', sa.Boolean(), nullable=False),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('model_number', sa.String(length=255), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_product_id', name='uq_market_product_source')
    )
    op.create_index(op.f('ix_market_products_brand'), 'market_products', ['brand'], unique=False)
    op.create_index(op.f('ix_market_products_category'), 'market_products', ['category'], unique=False)
    op.create_index(op.f('ix_market_products_model_number'), 'market_products', ['model_number'], unique=False)
    op.create_index(op.f('ix_market_products_sku'), 'market_products', ['sku'], unique=False)
    op.create_index(op.f('ix_market_products_source'), 'market_products', ['source'], unique=False)
    op.create_index(op.f('ix_market_products_source_product_id'), 'market_products', ['source_product_id'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_product_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['market_product_id'], ['market_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_history_market_product_id'), 'price_history', ['market_product_id'], unique=False)
    op.create_table('price_comparisons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lowest_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('highest_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('potential_savings', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('comparison_currency', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_comparisons_user_id'), 'price_comparisons', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_comparisons_user_id'), table_name='price_comparisons')
    op.drop_table('price_comparisons')
    op.drop_index(op.f('ix_price_history_market_product_id'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_market_products_source_product_id'), table_name='market_products')
    op.drop_index(op.f('ix_market_products_source'), table_name='market_products')
    op.drop_index(op.f('ix_market_products_sku'), table_name='market_products')
    op.drop_index(op.f('ix_market_products_model_number'), table_name='market_products')
    op.drop_index(op.f('ix_market_products_category'), table_name='market_products')
    op.drop_index(op.f('ix_market_products_brand'), table_name='market_products')
    op.drop_table('market_products')
    # ### end Alembic commands ###
